### ISSUE TITLE
Feature request: Bring back tabbed interface as an option

### ISSUE THREAD

**Issue by DMcCunney** [jecelyin/920-text-editor-v2#105]
On th earlier version of 920 Editor, you could edit multiple documents and have each appear in a tab listed on the top bar.  V2 appears to have multiple documents selectable from a panel that slide out from the left edge.  I actually prefer the tabbed interface, and would like that as an option.

---

Dennis

**Comment by JohnVeness** [comment]
I was just about to open the same issue, as I would like the same. Yes, the tabs were small so hard to see the full filename, but for my use case where I only had a few files and knew what they were, it was great for quickly switching between open files.

**Comment by DMcCunney** [comment]
Nice to see I'm not the only one.

Along that line, you can configure the font size used in the edit window.  I'd like to see it possible to adjust the font size on the 920 Editor menus as well.  On my 7" tablet, those are tiny, and can be a challenge to read.
