### ISSUE TITLE
Ability to adjust theme elements

### ISSUE THREAD

**Issue by DMcCunney** [jecelyin/920-text-editor-v2#115]
I have 920 Editor on a 7" Android tablet.  I normally use the Light theme.  On my screen, there elements can be a challenge to read, as in the screenshot below.

https://drive.google.com/open?id=0ByMy9Nx6Q5CiVlN2OXhwNGRjRGM

I'd like to be able to increase the font size in theme elements, and change the background color for better visibility.

**>Dennis**

**Comment by jecelyin** [comment]
Hi,
Thank you for your feedback first!
I am busy recently, if I have free time, I will collect your suggestions, and make a decision.

**Comment by DMcCunney** [comment]
That's fine.  I understand you have other things to do beside develop 920.  The need isn't critical, and I can wait till you have some time to look at it.  I just wanted to get the issue noted and into the tracker so it will be there when you do have time to look.

I'm just happy to see the 920 Editor and you back and development proceeding.

**>Dennis**
