### ISSUE TITLE
Editing seriously wrong since v2.17.8.16

### ISSUE THREAD

**Issue by JohnVeness** [jecelyin/920-text-editor-v2#1467]
With v2.17.8.16, editing is just seriously wrong for me. Every word I type gets strange characters before and after, and if move the cursor left and right (my on screen keyboard has left and right cursor keys) it moves the current word left and right!

Please see the screencast:
![screencast_2017-08-18-09-39-16](https://user-images.githubusercontent.com/2512915/29451099-512e2694-83f9-11e7-8cf9-d0d92f0f0594.gif)

**Comment by JohnVeness** [comment]
This seems to be related to word predictions in the on-screen keyboard. If I turn off predictions, the problem does not occur. I am using AnySoftKeyboard usually, but the problem occurs for me with all on screen keyboards that have predictions. The problem did not occur with older versions of 920.

**Comment by jecelyin** [comment]
fixed, thx

**Comment by JohnVeness** [comment]
Thanks for fixing the issue where extra characters were getting saved into the file.

However there still remains a visual glitch with extra spaces before and after a word while typing, and more annoyingly, the strange thing that happens if you move the cursor left and right.

This is the behaviour in the February release, which was perfect with regards to this issue:
![old](https://user-images.githubusercontent.com/2512915/29770234-ea235a92-8be5-11e7-8bda-fb30fe8b938b.gif)

This is the current behaviour:
![new](https://user-images.githubusercontent.com/2512915/29770246-f8b00aec-8be5-11e7-848f-4327bd516f37.gif)

**Comment by eyedarts** [comment]
I'm noticing similar, possibly related behavior, where after the auto complete displays the word in the editor, the cursor is placed before the word instead of after it. It's probably the same cause as the issue reported here. Let me know if it's not and I'll create another issue.
