### ISSUE TITLE
Backup filename changed with v2.17.8.16

### ISSUE THREAD

**Issue by JohnVeness** [jecelyin/920-text-editor-v2#1468]
Prior to v2.17.8.16, backups were named like .920bak.Test.txt. They are now named like Test.txt.bak.

Was this intentional? I preferred the old naming, as by default they were hidden in the UI. I have a lot of text files which I edit all the time, which will mean I'm ending up with double the length of list to scroll through when looking for a file in a folder, and I might easily accidentally open the .bak rather than the .txt and so accidentally not work on the latest version.

**Comment by jecelyin** [comment]
some device often create a hidden backup file failure, so I change backup file extension that look well.
