### ISSUE TITLE
"File changed" detection logic wrong since v2.17.8.16

### ISSUE THREAD

**Issue by JohnVeness** [jecelyin/920-text-editor-v2#1485]
In v2.17.8.16, if I edit a file but keep it the exact same size (e.g. change the word "One" to "Two"), 920 won't think the file has changed and so won't show the asterisk and will grey out the save icon. v2.17.2.13 had better file changed detection logic that would have detected such a change and allowed the user to save the file. My particular workflow is often changing files but keeping them the exact same size.

**Comment by jecelyin** [comment]
fixed
