### ISSUE TITLE
Backspace not working

### ISSUE THREAD

**Issue by eyedarts** [jecelyin/920-text-editor-v2#1519]
**Expected Behavior:**
Backspace key deletes previous character.

**Actual Behavior:**
Backspace key deletes multiple (maybe 2) characters.

Android 7.1.2 
Aug. 5th 2017 security patch 
Moto G3

**Comment by kenneth-Q** [comment]
I have same issue.
Any characters cannot delete. eg:enter
I hope this will fix son.

I like this app, add oil!

android 4.4.2
samsung note2

**Comment by eyedarts** [comment]
@jecelyin Is this problem fixed? Why was it closed?

**Comment by jecelyin** [comment]
I fix it now, but it need some time.
