### ISSUE TITLE
keystore folder is not their

### ISSUE THREAD

**Issue by guptahardik17** [jecelyin/920-text-editor-v2#1543]
Their is no keystore folder in this project.

I am getting error:

Error:(5, 0) E:\Android Apps\Project Trial\texteditor\keystore\920-text-editor-v2.gradle.properties (The system cannot find the path specified)

Please help

**Comment by jecelyin** [comment]
you can create it, the content example:

KEYSTORE_PASSWORD=
KEYSTORE_ALIAS=
GOOGLE_BILLING_KEY=
GITHUB_USER=
GITHUB_PWD=
