### ISSUE TITLE
I can't find 920 Text Editor...

### ISSUE THREAD

**Issue by tallship** [jecelyin/920-text-editor-v2#2]
I did a search at the Google Play Store but it turned up zero results for the 920 editor. Do you have a link to this (or perhaps it's not available for LG phones)?

When searching on F-Droid, the version I found was Version 12.11.23 - Added on 2012-12-05.

The status of the product had the following:

"Status: The app is now using resources from AOSP so it's unlikely we'll be able to update it."

What does that mean? I thought AOSP meant that everything was built according to the FOSS standards and 920 is GPL licensed too, right?

If the current version is not at the Play Store or F-Droid, will it be in either of those two places soon, or are there plans for it to be?

I like the editor and had it on an old Gingerbread phone but so far I've only installed the version above on my new phone from F-Droid.

Thank you in advance for any assistance in this matter that you are able to offer.

**Comment by jecelyin** [comment]
hi, the 920 text editor v2 is beta version, it's not release to google play,
you can down it from [https://github.com/jecelyin/920-text-editor-v2/releases](https://github.com/jecelyin/920-text-editor-v2/releases)
