### ISSUE TITLE
Missing files in source

### ISSUE THREAD

**Issue by herbert777** [jecelyin/920-text-editor-v2#23]
Hi,
I want to build this app from source but a whole folder is missing and the build fails.
The missing fodler is the databinding folder that should be located in file_explorer\src\main\java\com\jecelyin\android\file_explorer\databinding. There are 3 files inside, all needed for the build.
I don t understand why you removed it from the source but please, could you upload this folder somewhere?
Without it the code is useless since the app can t build.
Thanks in advance.

**Comment by 920-Text-Editor-User** [comment]
hi,
the databinding auto generated by Gradle.

android {

    dataBinding {
        enabled = true
    }

}

**Comment by herbert777** [comment]
Hi!
Thanks for our reply, it s working now.
But, there s a new issue...
Now it builds until 91%, but when it gets to the last compileReleaseJavaWithJavac it fails due to missing classes, mostly SuggestionRangeSpan.class and TemporaryBuffer.class.
Those classes can t be found in sdk/platforms/android-23/android.jar, and that s why the building returns errors.
It s strange because they are in sdk/sources/android-23/android.jar, but for some reasons they haven t been compiled to sdk/platforms/android-23/android.jar when the SDK manager installed android-23 on my computer.
I have tried uninstalling and reinstalling but it s still the same, the classes are not there.
I have tried compiling sdk/sources/android-23/android.jar by myself, but my small laptop can t handle it and returns out of memory errors, the file is too big for its limited specs:-(
I found those classes in sdk/platforms/android-23/data/layoutlib.jar, but I don t know what to do, the jar is pretty big (24.840 mb) so adding it as a dependency or library to Text Editor would make the app too heavy.
How did you manage to compile it?
Thanks in advance for your reply!
I sometimes compile using android studio, but most of the time I use the command line since

**Comment by herbert777** [comment]
I did some research, and I found out that those classes are in the source but not in the compiled android.jar because they are hidden API.
There are different ways to overcome that problem.
You can compile your own android.jar from sources (but as I said above as for me I can t since my computer isn t powerful enough), you can follow this tutorial:
https://devmaze.wordpress.com/2011/01/18/using-com-android-internal-part-1-introduction/
or you can download an already made android.jar from here:
https://github.com/anggrayudi/android-hidden-api
Well, that s all good but it still doesn t work, building shows the same errors with missing methods from for example SuggestionRangeSpan.class or TemporaryBuffer.class, but what is crazy is that I checked those classes and they do have the methods!
Any idea/suggestion is welcome, thanks in advance:-)

**Comment by jecelyin** [comment]
I uploaded Android.jar 
 [https://github.com/jecelyin/920-text-editor-v2/releases/tag/android.jar](url)

**Comment by herbert777** [comment]
Yesssssss, I downloaded your android.jar and it compiled!!!
Thank you very much for your help Sir, and thank you for this great app (I have been using 920 Text Editor since the old  days before version 2)!
