### ISSUE TITLE
Dark theme 

### ISSUE THREAD

**Issue by memeplex** [jecelyin/920-text-editor-v2#34]
That's the only basic feature I find it's missing. Otherwise, wonderful app.

**Comment by jecelyin** [comment]
it's coming soon..

**Comment by jecelyin** [comment]
added

**Comment by memeplex** [comment]
Hi @jecelyin, thank you for your work. I've installed the new version. Maybe it's me being just dumb but. I'm failing to find the dark theme option. Under the Theme and Highlighting section I just see a couple of highlighting related options.

**Comment by jecelyin** [comment]
press tab menu, you can see a clothing icon
