### ISSUE TITLE
[Question] Importing 920-text-editor-v2 project from github to android studio 2.2.3

### ISSUE THREAD

**Issue by daeseokyoun** [jecelyin/920-text-editor-v2#362]
Hello,

I tried to import this project to android studio 2.2.3 and built it.
But there are errors for building project.
 1) /920-text-editor-v2/app/src/main/java/com/jecelyin/editor/v2/core/text/SpannableStringBuilder.java
   Error:(24, 20) error: cannot find symbol class GraphicsOperations
   Error:(46, 21) error: cannot find symbol class GraphicsOperations

  2) /920-text-editor-v2/app/src/main/java/com/jecelyin/editor/v2/core/text/TextUtils.java
    Error:(50, 26) error: cannot find symbol class SuggestionRangeSpan

  3) /920-text-editor-v2/app/src/main/java/com/jecelyin/editor/v2/core/widget/Editor.java
    Error:(53, 26) error: cannot find symbol class SuggestionRangeSpan
    Error:(192, 5) error: cannot find symbol class SuggestionRangeSpan

  4) /920-text-editor-v2/app/src/main/java/com/jecelyin/editor/v2/core/text/TextLine.java
    Error:(24, 24) error: cannot find symbol class TemporaryBuffer

fixed issue by myself:
**import android.annotation.IntDef**; line should be changed to **import android.support.annotation.IntDef;**
in /home/jyoun/projects/920-text-editor-v2/styles/src/main/java/com/jecelyin/editor/v2/Pref.java.

Please give me answers to build this project.
Thanks.

**Comment by jecelyin** [comment]
please download android.jar from https://github.com/jecelyin/920-text-editor-v2/releases and replace your android sdk23 android.jar
