### ISSUE TITLE
Follow link functionality

### ISSUE THREAD

**Issue by memeplex** [jecelyin/920-text-editor-v2#41]
No android editor that I know of has support for following links. This would be a wonderful feature for people taking notes using plain text or markdown. I think mapping some gesture over something matching a url pattern to some "open in default browser" action would be enough.  

PS: @jecelyin I see you have been working on the markdown, dark theme and full screen features, thank you!

**Comment by jecelyin** [comment]
Sorry, match the URL need consume some performance, but will consider adding support.
