### ISSUE TITLE
能否提供选项默认以只读模式打开

### ISSUE THREAD

**Issue by renyouguo** [jecelyin/920-text-editor-v2#47]
终于找到了能在只读模式和编辑模式无缝切换的编辑器，非常感谢。
但我处理中文内容比较多，希望能默认以只读模式打开，需要了切换为编辑模式。

**Comment by jecelyin** [comment]
你选中只读模式，就都是只读模式了，看上去你是用的非最新的，麻烦下载最新的
[https://github.com/jecelyin/920-text-editor-v2/releases](https://github.com/jecelyin/920-text-editor-v2/releases)
