### ISSUE TITLE
Language rollback to Chinese 

### ISSUE THREAD

**Issue by benyaminl** [jecelyin/920-text-editor-v2#50]
Hello, 我是李嘉鉻，I'm having problem with the language interface, when I set the android language to Indonesian language, your program will rollback to Chinese or mandarin rather than english, I don't understand why but Would you like me help to translate or somekind? Thanks before

**Comment by luke67m** [comment]
I think i have the same problem. I use Italian language and i see your editor in Chinese. 
I'm translating strings.xml in italian and i will send you.
If you can set english as default , for me it's better.

**Comment by benyaminl** [comment]
Ah agree lah, maybe just fork this :v

Sent from my ASUS

-------- Pesan Awal --------
Dari:luke67m <notifications@github.com>
Terkirim:Mon, 29 Aug 2016 22:42:28 +0700
Kepada:jecelyin/920-text-editor-v2 <920-text-editor-v2@noreply.github.com>
Cc:Benyamin Limanto <BLBENYAMIN9@GMAIL.COM>,Author <author@noreply.github.com>
Subjek:Re: [jecelyin/920-text-editor-v2] Language rollback to Chinese (#50)

**Comment by luke67m** [comment]
Here the strings.xml in Italian(zipped).
Forking is not for me now.
I've asked to translate on GetLocalization(maybe easyer).
[strings.zip](https://github.com/jecelyin/920-text-editor-v2/files/447637/strings.zip)

**Comment by benyaminl** [comment]
@luke67m Wait, where's the file anyway? How can I find it? I see none of it on this repos

**Comment by luke67m** [comment]
Hi Benyamin, the file is attached to my previous comment : strings.zip.
Inside there is the strings.xml.
I hope it can be usefull.
I'm available to test a version with this translation.

**Comment by jecelyin** [comment]
I already publish new version fixed it,
now default language is english.

I will add Italian language on next version, thanks!
