### ISSUE TITLE
Bottom bar doesn't show up at all times

### ISSUE THREAD

**Issue by thewhitetulip** [jecelyin/920-text-editor-v2#52]
I recently found out that you are making a version2, thank you for that!

However, the bar which is present at the bottom doesn't show up always. It should be layered just above the keyboard.

I am using Hacker's keyboard.

**Comment by thewhitetulip** [comment]
Was it fixed? or is it an invalid bug? Because I found it to be the case in the latest update, no matter which keyboard I use, the bottom bar doesn't go above the keyboard, I have to make the keyboard go away to get the bar in place, which defeats the purpose of the bar.

**Comment by jecelyin** [comment]
hi, I will fix it on next version.
thanks
