### ISSUE TITLE
Market link in readme.md is incorrect

### ISSUE THREAD

**Issue by Gitoffthelawn** [jecelyin/920-text-editor-v2#57]
The link to get the app in the readme.md is incorrect.

Also, if this is offered in F-Droid, a link to that offering would be beneficial.

**Comment by jecelyin** [comment]
fixed, thank you!

**Comment by Gitoffthelawn** [comment]
You're welcome. I noticed there is no change to the readme!  Maybe you didn't get a chance to upload it?

**Comment by jecelyin** [comment]
I will merge dev branch to master branch on next version release

**Comment by Gitoffthelawn** [comment]
Sounds good!  Thanks!
