### ISSUE TITLE
Add new version to F-Droid

### ISSUE THREAD

**Issue by Gitoffthelawn** [jecelyin/920-text-editor-v2#59]
F-Droid only has the old version at https://jecelyin.github.io/920-Text-Editor-old

Can this version be added to F-Droid?

**Comment by Gitoffthelawn** [comment]
What are your thoughts on adding it?

**Comment by jecelyin** [comment]
It has been deprecated, I no longer update it.

**Comment by Gitoffthelawn** [comment]
Yes, can this version be added to F-Droid since the old one is deprecated?

**Comment by jecelyin** [comment]
what's Android version of your F-Droid phone?

**Comment by Gitoffthelawn** [comment]
KitKat
