### ISSUE TITLE
Highlighting never disappears after find

### ISSUE THREAD

**Issue by memeplex** [jecelyin/920-text-editor-v2#612]
After doing a find operation the highlighted match remains highlighted forever.

Also the highlight color makes the text almost impossible to read in dark theme.

**Comment by jecelyin** [comment]
> After doing a find operation the highlighted match remains highlighted forever.

I will fix it.

> Also the highlight color makes the text almost impossible to read in dark theme.

You can provide a screenshot?

**Comment by memeplex** [comment]
Sorry Jecelyin, I was not very specific: try highlighting (by searching it) a markdown header in the dark theme. If you can't reproduce I will upload the screenshot, but it's just orange on top of orange.
